# Site settings
baseurl = "http://innovationbox-uk.github.io/"
languageCode = "en-GB"
title = "Innovation Unboxed"
theme = "hugo-agency-theme"

Paginate = 3

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Innovation Unboxed"
	description = "innovation unboxed, social enterprise, charity, tech for good, tech support, digital advice, skilled volunteering, UK, corporate volunteering"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "contact@innovationunboxed.org"


	# Navigation
	[params.navigation]
		brand = "Innovation Unboxed"
		services = "Services"
		portfolio = "Portfolio"
		about = "About"
		news = "News"
		team = "Team"
		clients = "Partners"
		contact = "Contact"


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Innovation Unboxed"
		subtitle = "Changing the way charities and social enterprises engage with digital"
		buttonText = "Tell me more"

	# About section
	[params.about]
		title = "About"
		subtitle = "We use professional knowledge & expertise to fundamentally improve the use, access and deployment of technology in charities and social enterprises"

		[[params.about.list]]
			icon = "fa-group"
			title = "Support"
			description = "We bring together charities and social enterprises with skilled experts from the private sector to coach and support organisations to help them be clear about what they want to achieve and what technology and solution/supplier they need to achieve their goals."

		[[params.about.list]]
			icon = "fa-signal"
			title = "Effectiveness"
			description = "We provide specialist guidance to understand what charities and social enterprises are trying to do as an organisation, and the most effective and impactful way to achieve that."

		[[params.about.list]]
			icon = "fa-line-chart"
			title = "Impact"
			description = "Ultimately we want to leverage technology to help charities and social enterprises find better ways to raise funds, manage internal systems and reach beneficiaries."


	# Services section - currently disabled
	[params.services]
		title = "Services"
		subtitle = "Services - What we provide."

		[[params.services.list]]
			icon = "fa-shopping-cart"
			title = "E-Commerce"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

		[[params.services.list]]
			icon = "fa-laptop"
			title = "Responsive Design"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

		[[params.services.list]]
			icon = "fa-lock"
			title = "Web"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."


	# Portfolio section - currently disabled
	[params.portfolio]
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Portfolio"
		subtitle = "Lorem ipsum dolor sit amet consectetur."

		[params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttonText = "Close project"

	# Team section
	[params.team]
		title = "The team"
		subtitle = ""
		description = ""

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "HelenParry.jpg"
			name = "Helen Lang"
			position = "Founder, Director"
			bio = "Experienced strategic manager with a record of delivering successful growth in organisations. With over 10 years project management, innovation, fundraising, and delivery experience, (working both in the UK and overseas) and a passion for high quality delivery and concrete outcomes. "
			social = [
				["fa-twitter", "https://twitter.com/iboxforgood"],
				["fa-linkedin", "https://uk.linkedin.com/in/helenlang"]
			]


			[params.advisory]
				title = "Advisory Board"
				subtitle = "World class business leaders."

			# All advisory member's pictures are stored under 'static/img/advisory'.
			# Replace them with your own too.
			[[params.team.advisory]]
				img = "BruceMacMillan.jpg"
				name = "Bruce Macmillan"
				position = "Director GC Academy, RPC"
				bio = "Bruce Macmillan is founding Director of the RPC (law firm) Centre for Legal Leadership. The Centre is an initiative commenced in 2016 to provide coaching, mentoring, networking, education and training to in house legal teams on all aspects of their role.  Between 2014 and 2016 Bruce worked jointly as the General Counsel of Legal Practice Technologies Limited and as a management consultant and coach specialising in the legal services sector. Bruce was Executive Director, Senior Commercial Legal Counsel at VISA Europe until April 2014."

			[[params.team.advisory]]
				img = "no-photo.png"
				name = "Gareth Johnson"
				position = "COO, Rothschild Wealth Management"
				bio = "Wealth Management and the Head of their Investment platform, His specialisms are asset management, portfolio management, investment and project management.  Prior to joining Rothschild spent 12 years at Morgan Stanley. Gareth was the COO of Morgan Stanley, Global Investment Solutions"

			[[params.team.advisory]]
				img = "Jean-FrancoisSchmid.jpg"
				name = "Jean-Francois Schmid"
				position = "Global Transformation Director, BBC Worldwide"
				bio = "Prior to BBCW, Jean Francois worked for BT in the IT/ technology areas, driving the longer term innovation agenda for BT and restructuring the research function to make it more strategic and better aligned to the business.  Prior to BT, Jean Francois worked for Cable & Wireless in Group Strategy, driving the strategic planning process for the units outside of the UK. He also spent 5 years in New York city working for AT Kearney, a management consultant in a variety of strategic, operational and IT projects. "

			[[params.team.advisory]]
				img = "AlanCrawford.jpg"
				name = "Alan Crawford"
				position = "Chief Information Officer, City & Guilds"
				bio = "Chief Information Officer at City & Guilds, a global leader in skills development, helping people into a job, on the job, and onto the next job. Alan was a winner of the UK Digital Leaders 100 - Charity Digital Leader of the Year 2016 award."

			[[params.team.advisory]]
				img = "Phil.jpg"
				name = "Phil Sutcliffe"
				position = "Board Director, TNS UK"
				bio = "Phil has worked in the research industry for over 20 years, both in the UK and in Japan. He focuses on innovation in research and the challenges that clients face - working to develop the best possible solutions that TNS UK can offer.  Phil has been instrumental in driving many of our research solutions, from leading our specialist research practices, to our marketing science and digital teams. He continues to support and develop the innovation of our offer and creating greater impact across the business. This includes training, coaching, building capability and optimising our day to day processes."

			[[params.team.advisory]]
				img = "SteveR.jpg"
				name = "Steve Rich"
				position = "Director, Ooredoo Group"
				bio = "Steve is a corporate lawyer with over 15 years of experience gained in leading international law firms and global companies in North America, the Middle East, Southeast Asia, and Europe.  He has experience of dealing with a wide range of transactional, commercial, and regulatory matters, with a focus on the telecommunications and technology sectors."

			[[params.team.advisory]]
				img = "Akira.jpg"
				name = "Akira Kirton"
				position = "Co-Head of BP Ventures, BP"
				bio = "BP Ventures makes strategic investments in companies with distinctive technology that aligns with BP core businesses. Akira’s previous professional experience include working within and then supporting the spin-out of a company serving over two million persons with energy solutions in rural India and a three year secondment to the UK Energy Technologies Institute (a billion dollar public private partnership between the UK government and industry focused on accelerating affordable, sustainable energy technologies). Akira is a recipient of the 2008 IChemE Award for Innovation, a 2012 Fellow of the Marshall Memorial Foundation and a 2015 World Economic Forum Young Global Leader Award winner."

	# Team section
	[params.clients]
		title = "Partners"
		subtitle = ""
		description = ""

			# All the clients' logos are stored under 'static/img/logos'.
			# Replace them with your clients's logos.
			[[params.clients.client]]
				logo = "comic_relief.png"
				link = "https://www.comicrelief.com/"

			[[params.clients.client]]
				logo = "cast.jpg"
				link = "http://www.wearecast.org.uk/"

			[[params.clients.client]]
				logo = "tender.png"
				link = "http://tender.org.uk/"

			[[params.clients.client]]
					logo = "group_m.png"
					link = "https://www.groupm.com/"

			[[params.clients.client]]
				logo = "aanchal.png"
				link = "http://aanchal.org.uk/"

			[[params.clients.client]]
				logo = "sse_fellow.png"
				link = "https://www.the-sse.org"

	[params.quotes]
		title = "Feedback"
		subtitle = ""
		description = ""

		[[params.quotes.quote]]
			person = "Nominet Trust, Chris Ashworth"
			text = "It was great to work with Innovation Unboxed on the design and content of our 'charity digital usage research' study, her knowledge and understanding of the sector and issues proved invaluable. The work she invested in the structure, content and design of the survey have meant that we have been able to take forward an important piece of work that will both give us a more insightful and practical understanding of the types of interventions or support we will need to think about in the future."

		[[params.quotes.quote]]
			person = "Aanchal"
			text = "Our experience with Innovation Unboxed can be described as a breath of fresh air, not only supporting us in one particular project, but helping us to think outside the box across our organisation.  Each activity giving us further links into growth and sustainability.  We have found this partnership very grounded, adapting to what we know already, learning together and then raising the bar to help us realise our potential.  Helen gives more than what you ask for, for example, we have learnt new tools to establish our evidence and planning ahead in a short space of time."

	# Contact section
	[params.contact]
		title = "Contact us"
		subtitle  = "Please drop us a line."
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
		copyright = ""

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "https://twitter.com/iboxforgood"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "https://uk.linkedin.com/in/helenlang"

		[[params.footer.quicklinks]]
			text = "Terms of Use"
			link = "/terms"
